name: Correção

on:
  push: 
    branches: [ "gh-pages" ]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
  
      - name: Build Jekyll
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Preparação dos testes
        uses: actions/setup-node@v2
        with: 
          node-version: 16.x
          cache: 'npm'
      - name: Configuração das dependências
        uses: ./.github/actions/public-grading
        run: npm install

      - name: Execução dos testes
        run: npm test