name: Correção

on:
  push: 
    branches: [ "gh-pages" ]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
  
      - name: 2a etapa
        uses: ./.github/actions/public-grading

      - name: Configurando dependências
        run: npm install

      - name: Executando testes
        run: npm test